import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import AuthProvider from '@/components/Provider/AuthProvider';
import ToastProvider from '@/components/Provider/ToastProvider';
import RecoilProvider from '@/components/Provider/RecoilProvider';
import SideBar from '@/components/SideBar';
import Header from '@/components/Header';

const pretendard = localFont({
  src: [
    {
      path: '../../public/fonts/Pretendard-Thin.otf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Black.otf',
      weight: '900',
      style: 'normal',
    },
  ],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <RecoilProvider>
          <AuthProvider>
            <ToastProvider>
              <Header />
              <SideBar />
              <main className="pt-[130px] pr-[50px] pl-[310px] pb-[30px]">
                {children}
              </main>
            </ToastProvider>
          </AuthProvider>
        </RecoilProvider>
      </body>
    </html>
  );
}
